apiVersion: v1
kind: Service
metadata:
  name: yara-oke-app-service
  namespace: yara-app
spec:
  type: LoadBalancer
  selector:
    app: yara-oke-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80